version: '0.0.{build}'

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  global:
    PYTHON: "C:\\Python36"
    CYG_ROOT: C:\cygwin64

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86_64
    platform: x64
    visual_studio: Visual Studio 16 2019
    compiler_toolset: v142
    gtest: 1.10.0

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    compiler_toolset: v141
    gtest: 1.10.0

install:
  - "SET PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%"
  - pip.exe install conan
  - conan user
  - conan remote add systelab-public https://csw.jfrog.io/artifactory/api/conan/cpp-conan-production-local --insert 0
  - conan --version

before_build:
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST% --build  missing
  - cmake .. -G "%VISUAL_STUDIO%" -A %PLATFORM%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\GTestAllureUtilities.sln

after_build:
  - conan export-pkg ../conanfile.py GTestAllureUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST%
  - conan test ../test_package/conanfile.py GTestAllureUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST%

test_script:
  - ps: cd bin
  - ps: cd $env:CONFIGURATION
  - UnitTest.exe --gtest_output=xml:../UnitTest.xml
  - IntegrationTest.exe --gtest_output=xml:../IntegrationTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ..\UnitTest.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ..\IntegrationTest.xml))

artifacts:
  - path: 'build\lib\%CONFIGURATION%\GTestAllureUtilities.lib'
    name: GTestAllureUtilities.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload GTestAllureUtilities/$env:appveyor_build_version@systelab/stable --all -r systelab-public --force
      } else {
        echo "Not uploading because this is not a tag build"
      }
  - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./ci/build_docs.sh -o \"systelab\" -s \"cpp-gtest-allure-utilities\" -t \"$APPVEYOR_REPO_TAG_NAME\" -c AppVeyor -n \"$APPVEYOR_BUILD_WORKER_IMAGE %PLATFORM% %CONFIGURATION%\" -j \"$APPVEYOR_JOB_ID\" -p \"UnitTest,IntegrationTest\"'
